/**
 * 
 */
package com.atsistemas.mamp.ecommerce.payment.common;


/**
 * 
 *
 */
public interface IConstantsIngenico {

	String SPACE = " ";
	int maxSendDataRetries = 3;
	
	String connectionFailed = "connection.failed";
	String paymentResponseNotIdentified = "payment.response.notIdentified";
	String pleaseContactAdministrator = "please.contact.administrator";
	String wrongContentTypeAliasGatewayResponse = "wrong.content.type.alias.gateway.response";
	String originalError = "error.original";
	
	String ERROR_RESULT = "error";
	String OK_RESULT = "ok";
	String ERROR_MESSAGE_SEPARATOR = "#-#";
	
	String SDK_CONFIG_NODE_COMMON_NAME = "common";
	
	String SDK_CONFIG_PROP_API_USER_PSWD = "api.userPswd";
	String SDK_CONFIG_PROP_API_USER_ID = "api.userId";
	String SDK_CONFIG_PROP_ACCEPT_URL = "acceptUrl";
	String SDK_CONFIG_PROP_DECLINE_URL = "declineUrl";
	String SDK_CONFIG_PROP_EXCEPTION_URL = "exceptionUrl";
	String SDK_CONFIG_PROP_OK_URL = "okUrl";
	String SDK_CONFIG_PROP_KO_URL = "koUrl";
	String SDK_CONFIG_PROP_PSPID = "pspId";
	String SDK_CONFIG_PROP_API_PASSPHRASE_SHAIN = "api.passphrase.sha.in";
	String SDK_CONFIG_PROP_API_PASSPHRASE_SHAOUT = "api.passphrase.sha.out";
	String SDK_CONFIG_PROP_ENDPOINT_ALIAS_GATEWAY = "service.endpoint.alias.gateway";
	String SDK_CONFIG_PROP_ENDPOINT_DIRECT_LINK = "service.endpoint.direct.link";
	String SDK_CONFIG_PROP_ENDPOINT_PAYPAL = "service.endpoint.paypal";

	String MGNL_CTX_ATTR_INGENICO_CURRENT_SITE = "site";

	/** ALIAS GATEWAY **/
	
	String USER_AGENT_HEADER_ATTR = "User-Agent";
	String USER_AGENT = "Mozilla/5.0";
	String LOCATION_HEADER_RESPONSE_PARAM = "Location";
	String ALIAS_GATEWAY_RESPONSE_CONTENT_TYPE = "text/html";
	
	String INPUT_FIELD_ACCEPT_URL = "ACCEPTURL";
	String INPUT_FIELD_BRAND_CARD = "BRAND";
	String INPUT_FIELD_CARD_NO = "CARDNO";
	String INPUT_FIELD_CARD_HOLDER = "CN";
	String INPUT_FIELD_CVC = "CVC";
	String INPUT_FIELD_EXPIRATION_DATE = "ED";
	String INPUT_FIELD_EXCEPTION_URL = "EXCEPTIONURL";
	String INPUT_FIELD_ORDER_ID = "ORDERID";
	String INPUT_FIELD_MERCHANT_ID = "PSPID";
	String INPUT_FIELD_SHA_HASH = "SHASIGN";

	String OUTPUT_FIELD_ALIAS_GATEWAY_ALIAS = "Alias";
	String OUTPUT_FIELD_ALIAS_GATEWAY_NCERROR = "NCError";
	String OUTPUT_FIELD_ALIAS_GATEWAY_NCERRORCN = "NCErrorCN";
	String OUTPUT_FIELD_ALIAS_GATEWAY_NCERRORCARDNO = "NCErrorCardNo";
	String OUTPUT_FIELD_ALIAS_GATEWAY_NCERRORCVC = "NCErrorCVC";
	String OUTPUT_FIELD_ALIAS_GATEWAY_NCERRORED = "NCErrorED";
	String OUTPUT_FIELD_DIRECT_LINK_PAYID = "PAYID";
	String OUTPUT_FIELD_DIRECT_LINK_NCERROR = "NCERROR";
	String OUTPUT_FIELD_DIRECT_LINK_NCERRORPLUS = "NCERRORPLUS";
	String OUTPUT_FIELD_NO_ERROR_VALUE = "0";
	
	String ALIAS_GATEWAY_KEY_MESSAGE_ROOT_PATH_ERROR = "alias.gateway.error.";
	String ALIAS_GATEWAY_KEY_MESSAGE_ROOT_PATH_PERSONALIZED_ERROR = "alias.gateway.personalizedError.";
	
	String ALIAS_GATEWAY_KEY_MESSAGE_FINAL_PATH_PERSONALIZED_ERROR = "aliasNotFound";
	
	
	/** DIRECTLINK **/
	
	String CONTENT_TYPE_HEADER_ATTR = "Content-Type";
	String CONTENT_TYPE_FORM_URL_ENCODED = "application/x-www-form-urlencoded";
	
	String DIRECT_LINK_KEY_MESSAGE_ROOT_PATH_ERROR = "direct.link.error.";
	
	String OPERATION_SALE = "SAL";
	
	String INPUT_FIELD_USER_ID = "USERID";
	String INPUT_FIELD_PSWD = "PSWD";
	String INPUT_FIELD_ALIAS = "ALIAS";
	String INPUT_FIELD_AMOUNT = "AMOUNT";
	String INPUT_FIELD_CURRENCY = "CURRENCY";
	String INPUT_FIELD_OPERATION = "OPERATION";
	
	
	/** PAYPAL INTEGRATION **/
	
	String PAYPAL_INGENICO_SERVLET_RELATIVE_PATH = "/.PaypalIngenicoServlet";
	
	String ATTR_PAYPAL_STEP_ACCEPT_URL_PARAMETER = "phase";
	String VAL_IDENTIFICATION_PAYPAL_STEP_ACCEPT_URL_PARAMETER = "identificationResult";
	String VAL_PAYMENT_PAYPAL_STEP_ACCEPT_URL_PARAMETER = "paymentResult";
	
	String MGNL_CTX_VAL_PAYPAL_STEP_IDENTIFICATION = "identification";
	String MGNL_CTX_VAL_PAYPAL_STEP_PAYMENT_DONE = "paymentDone";
	
	String CONTEXT_ATTRIBUTE_PAY_METHOD = "method";
	String PAY_METHOD_PAY_PAL_TEXT = "payPal";
	String PAYPAL_ORDER_PARAM_ORDER_ID = "orderId";
	String PAYPAL_ORDER_PARAM_TRANSACTION_ID = "transactionId";
	
	String INPUT_FIELD_PAYPAL_MERCHANT_ID = "PSPID";
	String INPUT_FIELD_PAYPAL_USER_ID = "USERID";
	String INPUT_FIELD_PAYPAL_PSWD = "PSWD";
	String INPUT_FIELD_PAYPAL_ORDER_ID = "ORDERID";
	String INPUT_FIELD_PAYPAL_AMOUNT = "AMOUNT";
	String INPUT_FIELD_PAYPAL_CURRENCY = "CURRENCY";
	String INPUT_FIELD_LANGUAGE = "LANGUAGE";
	String INPUT_FIELD_PAYPAL_ACCEPT_URL = "ACCEPTURL";
	String INPUT_FIELD_DECLINE_URL = "DECLINEURL";
	String INPUT_FIELD_PM = "PM";
	String INPUT_FIELD_TX_TOKEN = "TXTOKEN";
	String INPUT_FIELD_DEVICE = "DEVICE";
	String INPUT_FIELD_PAYPAL_PAY_ID = "PAYID";
	String INPUT_FIELD_PAYPAL_OPERATION = "OPERATION";
	String INPUT_FIELD_PAYPAL_SHA_HASH = "SHASIGN";
	
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_EMAIL = "PayerEmail";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_ID = "PayerID";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_STATUS = "PayerStatus";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_SALUTATION = "PayerSalutation";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_FIRST_NAME = "PayerFirstName";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_MIDDLE_NAME = "PayerMiddleName";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_LAST_NAME = "PayerlastName";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_SUFFIX = "PayerSuffix";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_COUNTRY = "PayerCountry";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_BUSINESS = "PayerBusiness";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_ADR_STATUS = "PayerAdrStatus";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_ADR_NAME = "PayerAdrName";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_ADR_STREET1 = "PayerAdrStreet1";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_ADR_STREET2 = "PayerAdrStreet2";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_ADR_CITYNAME = "PayerAdrCityName";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_ADR_STATEORPROVINCE = "PayerAdrStateOrProvince";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_ADR_POSTALCODE = "PayerAdrPostalCode";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYER_ADR_COUNTRY = "PayerAdrCountry";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_CUSTOM = "Custom";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_INVOICE_ID = "InvoiceID";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_CONTACT_PHONE = "ContactPhone";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PSPID = "PSPID";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_ORDER_ID = "orderID";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_CURRENCY = "currency";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_AMOUNT = "amount";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_TXTOKEN = "TXTOKEN";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_PAYID = "PAYID";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_SHASIGN = "SHASIGN";
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_AUTHENT_STATUS = "AuthentStatus";
	
	String OUTPUT_FIELD_PAYPAL_IDENTIFICATION_NO_ERROR_VALUE = "0";
	
	String PAYPAL_IDENTIFICATION_KEY_MESSAGE_ROOT_PATH_ERROR = "paypal.identification.error.";
	String PAYPAL_IDENTIFICATION_KEY_MESSAGE_SHA_OUT_ERROR = PAYPAL_IDENTIFICATION_KEY_MESSAGE_ROOT_PATH_ERROR + "shaout";
	String PAYPAL_IDENTIFICATION_KEY_MESSAGE_AUTHENTICATION_ERROR = PAYPAL_IDENTIFICATION_KEY_MESSAGE_ROOT_PATH_ERROR + "authentication";
	String PAYPAL_IDENTIFICATION_KEY_MESSAGE_SITE_NOT_FOUND_ERROR = PAYPAL_IDENTIFICATION_KEY_MESSAGE_ROOT_PATH_ERROR + "site.not.found";
	String PAYPAL_IDENTIFICATION_KEY_MESSAGE_PAYMENT_URL_NOT_FOUND_ERROR = PAYPAL_IDENTIFICATION_KEY_MESSAGE_ROOT_PATH_ERROR + "payment.url.not.found";
	String PAYPAL_IDENTIFICATION_KEY_MESSAGE_PAYMENT_PENDING_ERROR = PAYPAL_IDENTIFICATION_KEY_MESSAGE_ROOT_PATH_ERROR + "payment.pending";
	String PAYPAL_IDENTIFICATION_KEY_MESSAGE_PAYMENT_DATA_NOT_FOUND_ERROR = PAYPAL_IDENTIFICATION_KEY_MESSAGE_ROOT_PATH_ERROR + "payment.data.not.found";

	String OUTPUT_FIELD_PAYPAL_PAYMENT_AAV_CHECK = "AAVCheck";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_ACCEPTANCE = "ACCEPTANCE";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_AMOUNT = "amount";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_BRAND = "BRAND";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_CARDNO = "CARDNO";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_CCCTY = "CCCTY";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_CN = "CN";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_CURRENCY = "currency";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_CVC_CHECK = "CVCCheck";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_DCC_COMMPERCENTAGE = "DCC_COMMPERCENTAGE";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_DCC_CONVAMOUNT = "DCC_CONVAMOUNT";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_DCC_CONVCCY = "DCC_CONVCCY";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_DCC_EXCHRATE = "DCC_EXCHRATE";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_DCC_EXCHRATESOURCE = "DCC_EXCHRATESOURCE";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_DCC_EXCHRATETS = "DCC_EXCHRATETS";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_DCC_INDICATOR = "DCC_INDICATOR";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_DCC_MARGINPERCENTAGE = "DCC_MARGINPERCENTAGE";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_DCC_VALIDHOURS = "DCC_VALIDHOURS";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_ECI = "ECI";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_ED = "ED";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_IP = "IP";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_IPCTY = "IPCTY";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_NCERROR = "NCERROR";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_ORDER_ID = "orderID";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_PAYID = "PAYID";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_PAYID_SUB = "PAYIDSUB";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_PM = "PM";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_SCO_CATEGORY = "SCO_CATEGORY";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_SCORING = "SCORING";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_STATUS = "STATUS";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_TRXDATE = "TRXDATE";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_VC = "VC";
	String OUTPUT_FIELD_PAYPAL_PAYMENT_SHASIGN = "SHASIGN";
	
	String OUTPUT_FIELD_PAYPAL_PAYMENT_NO_ERROR_VALUE = "0";
	
	String PAYPAL_PAYMENT_KEY_MESSAGE_SHA_OUT_ERROR = "paypal.payment.error.shaout";
	
}
